<?php
// Database connection details
$servername = "localhost"; // Change this to your database server
$username = "root"; // Change this to your database username
$password = ""; // Change this to your database password
$dbname = "nexteaze"; // Change this to your database name

// Create a connection
$conn = new mysqli($servername, $username, $password, $dbname);

// Check the connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

// Start session
session_start();

// Assume the user is 'admin' or replace with a dynamic user value
$user = 'admin';

// Handle the form submission
$status = $_POST['status'] ?? '';
$downloadType = $_POST['download_type'] ?? '';
$selectedCodes = $_POST['selected_codes'] ?? [];

// Prepare base query
$query = "SELECT id, code, created_at, prefix, postfix, length, quantity, status, generated_by FROM verification_codes WHERE generated_by = ?";
$params = [$user];

// Add status filter if specified
if ($status !== '') {
    $query .= " AND status = ?";
    $params[] = $status;
}

// Add a condition for selected codes if specified
if ($downloadType === 'selected' && !empty($selectedCodes)) {
    $placeholders = implode(',', array_fill(0, count($selectedCodes), '?'));
    $query .= " AND code IN ($placeholders)";
    $params = array_merge($params, $selectedCodes);
}

// Prepare and execute the query
$stmt = $conn->prepare($query);
$stmt->bind_param(str_repeat('s', count($params)), ...$params);
$stmt->execute();
$result = $stmt->get_result();

// Open output stream for file download
header('Content-Type: text/csv');
header('Content-Disposition: attachment;filename="codes.csv"');

// Output CSV header
$output = fopen('php://output', 'w');
fputcsv($output, ['ID', 'Code', 'Created At', 'Prefix', 'Postfix', 'Length', 'Quantity', 'Status', 'Generated By']);

// Output CSV data
while ($row = $result->fetch_assoc()) {
    fputcsv($output, $row);
}

fclose($output);
$stmt->close();
$conn->close();
exit;
?>

<!-- JavaScript for Dynamic Checkboxes -->
<script>
document.addEventListener("DOMContentLoaded", function() {
    const form = document.querySelector('form[action="download_codes.php"]');
    const downloadTypeRadio = document.querySelectorAll('input[name="download_type"]');
    const selectedCodesContainer = document.getElementById('selected_codes_container');

    // Function to generate checkboxes
    function generateCheckboxes(codes) {
        selectedCodesContainer.innerHTML = ''; // Clear existing checkboxes
        codes.forEach(code => {
            const checkbox = document.createElement('div');
            checkbox.classList.add('form-check');
            checkbox.innerHTML = `
                <input type="checkbox" id="code_${code.id}" name="selected_codes[]" value="${code.code}" class="form-check-input">
                <label for="code_${code.id}" class="form-check-label">${code.code}</label>
            `;
            selectedCodesContainer.appendChild(checkbox);
        });
    }

    // Event listener for radio buttons
    downloadTypeRadio.forEach(radio => {
        radio.addEventListener('change', function() {
            if (this.value === 'selected') {
                // Fetch codes via AJAX or by including them in the page (example using static data here)
                const codes = [ /* Array of code objects { id: 1, code: 'ABC123' } */ ]; 
                generateCheckboxes(codes);
            } else {
                selectedCodesContainer.innerHTML = ''; // Clear checkboxes
            }
        });
    });
});
</script>
