<!DOCTYPE html>
<?php

include 'sec.php';
// Update the last activity time
$_SESSION['last_activity'] = time();

// Check if user is logged in and retrieve user email
if (!isset($_SESSION['email'])) {
    header("Location: /signin"); // Redirect to login page if not logged in
    exit;
}

$logged_in_user = $_SESSION['email']; // Get the logged-in user's email
$title = 'Verify Codes';

include '../common/db.php';

// Initialize variables
$test_verification_result = '';
$user_verification_result = '';
$test_code_data = '';
$user_code_data = '';

// Handle form submission for testing
if (isset($_POST['test_code'])) {
    $code_to_verify = $_POST['test_code'];

    // Prepare and bind: Only check codes generated by the logged-in user
    $stmt = $conn->prepare("SELECT id, code, prefix, postfix, length, status FROM verification_codes WHERE code = ? AND generated_by = ?");
    if ($stmt) {
        $stmt->bind_param("ss", $code_to_verify, $logged_in_user);
        $stmt->execute();
        $result = $stmt->get_result();

        if ($result->num_rows > 0) {
            $test_verification_result = 'Test Code exists.';
            $test_code_data = $result->fetch_assoc();
        } else {
            $test_verification_result = 'Test Code not found or you did not generate this code.';
        }

        $stmt->close(); // Close the statement after use
    } else {
        $test_verification_result = 'Error preparing statement.';
    }
}

// Handle form submission for users
if (isset($_POST['user_code'])) {
    $code_to_verify = $_POST['user_code'];

    // Prepare and bind: Only check codes generated by the logged-in user
    $stmt = $conn->prepare("SELECT id, code, prefix, postfix, length, status FROM verification_codes WHERE code = ? AND generated_by = ?");
    if ($stmt) {
        $stmt->bind_param("ss", $code_to_verify, $logged_in_user);
        $stmt->execute();
        $result = $stmt->get_result();

        if ($result->num_rows > 0) {
            $user_verification_result = 'Congratulations! User Code exists.';
            $user_code_data = $result->fetch_assoc();

            // Close the statement before reusing it for update
            $stmt->close();

            // Prepare and execute update statement
            $stmt = $conn->prepare("UPDATE verification_codes SET status = 'Used' WHERE code = ? AND generated_by = ?");
            if ($stmt) {
                $stmt->bind_param("ss", $code_to_verify, $logged_in_user);
                $stmt->execute();
                $stmt->close(); // Close the statement after use
            } else {
                $user_verification_result = 'Error preparing update statement.';
            }
        } else {
            $user_verification_result = 'User Code not found or you did not generate this code.';
        }
    } else {
        $user_verification_result = 'Error preparing statement.';
    }
}

$conn->close();
?>

<html lang="en">
<?php include '../common/admin-head.php' ?>

<body>
    <main class="page-wrapper rbt-dashboard-page">
        <div class="rbt-panel-wrapper">
            <?php include '../common/header.php'; ?>
            <?php include '../common/mobilemenu.php'; ?>
            <?php include '../common/Leftpanel.php'; ?>

            <div class="rbt-main-content mr--0">
                <div class="rbt-daynamic-page-content">
                    <div class="rbt-dashboard-content">
                        <div class="content-page">
                            <div class="container mt-4">
                                <div class="section-title text-center sal-animate" data-sal="slide-up">
                                    <h2 class="title w-600 mb--20">Verify Product Verification Codes</h2>
                                    <p class="description b1">Enter a verification code to check its validity.</p>
                                </div>

                                <!-- Testing Form -->
                                <div class="section-title text-center sal-animate">
                                    <div class="col-lg">
                                        <div class="card shadow-sm rbt-static-bar">
                                            <h3>Test Code Verification</h3>
                                            <form method="post" action="verify-codes" class="row g-3 align-items-center new-chat-form border-gradient" id="test-code-form">
                                                <div class="col-md-6">
                                                    <label for="test_code" class="form-label">Test Code</label>
                                                    <input type="text" class="form-control border-gradient" id="test_code" name="test_code" placeholder="Enter code" required>
                                                </div>
                                                <div class="col-md-6 d-flex align-items-center">
                                                    <button type="submit" class="btn-default btn-small round w-100">Verify Test Code</button>
                                                </div>
                                            </form>

                                            <!-- Display Test Verification Result -->
                                            <?php if (!empty($test_verification_result)) : ?>
                                                <div class="mt-4">
                                                    <p class="result"><?php echo htmlspecialchars($test_verification_result); ?></p>
                                                    <?php if (!empty($test_code_data)) : ?>
                                                        <table class="table table-bordered">
                                                            <thead>
                                                                <tr>
                                                                    <th>Code</th>
                                                                    <th>Prefix</th>
                                                                    <th>Postfix</th>
                                                                    <th>Length</th>
                                                                    <th>Status</th>
                                                                </tr>
                                                            </thead>
                                                            <tbody>
                                                                <tr>
                                                                    <td><?php echo htmlspecialchars($test_code_data['code']); ?></td>
                                                                    <td><?php echo htmlspecialchars($test_code_data['prefix']); ?></td>
                                                                    <td><?php echo htmlspecialchars($test_code_data['postfix']); ?></td>
                                                                    <td><?php echo htmlspecialchars($test_code_data['length']); ?></td>
                                                                    <td><?php echo htmlspecialchars($test_code_data['status']); ?></td>
                                                                </tr>
                                                            </tbody>
                                                        </table>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>


                        </div>
                    </div>
                </div>

                <script>
                    <?php if (!empty($user_verification_result) && strpos($user_verification_result, 'Congratulations') !== false) : ?>
                        Swal.fire({
                            title: 'Congratulations!',
                            text: '<?php echo htmlspecialchars($user_verification_result); ?>',
                            icon: 'success',
                            confirmButtonText: 'OK'
                        });
                    <?php endif; ?>
                </script>
            </div>
        </div>
    </main>
</body>

</html>
